# Generated by Django 5.1.7 on 2025-03-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Blog',
            new_name='blog',
        ),
    ]
