# Generated by Django 5.1.7 on 2025-03-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_blog_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='Blog',
            new_name='blog',
        ),
    ]
